[package]
name = "md2md"
version = "0.1.0"
edition = "2021"
authors = ["Andy Sadler"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.1.9", features = ["derive"] }
color-eyre = "0.6.2"
once_cell = "1.17.1"
regex = "1.7.1"
winnow = { version = "0.3.5", features = ["simd"] }
