[package]
name = "rust-markdown-extra-extended"
version.workspace = true
edition.workspace = true

[dependencies]
pulldown-cmark = "0.9.2"
regex = "1.7.1"
winnow = { version = "0.3.5", features = ["simd"] }
